import { defineField, defineType } from 'sanity'

export const pageContent = defineType({
  name: 'pageContent',
  title: 'Page & Section Content',
  type: 'document',
  fields: [
    defineField({
      name: 'pageId',
      title: 'Page / Section',
      type: 'string',
      options: {
        list: [
          { title: 'Menu Page', value: 'menu' },
          { title: 'Lamesa Page', value: 'lamesa' },
          { title: 'Grocery Page', value: 'grocery' },
          { title: 'Filipiniana at IBP Page', value: 'filipiniana' },
          { title: 'Section: Weekly Specials', value: 'section-specials' },
          { title: 'Section: Sweet Delights (Desserts)', value: 'section-desserts' },
          { title: 'Section: Meet Our Team', value: 'section-team' },
          { title: 'Section: Loved by the Community (Testimonials)', value: 'section-testimonials' },
          { title: 'Section: Visit Us (Contact)', value: 'section-contact' },
          { title: 'Section: Our Menu (Home)', value: 'section-menu' },
          { title: 'Section: Delicious Soup', value: 'section-soups' },
          { title: 'Section: Gallery', value: 'section-gallery' },
          { title: 'Section: Announcements', value: 'section-announcements' },
        ],
      },
      validation: (Rule) => Rule.required(),
    }),
    defineField({ name: 'title', title: 'Title', type: 'string', validation: (Rule) => Rule.required() }),
    defineField({ name: 'subtitle', title: 'Subtitle', type: 'text', rows: 2 }),
    defineField({ name: 'body', title: 'Body Text', type: 'text', rows: 5, hidden: ({ document }) => document?.pageId !== 'lamesa' }),
    defineField({ name: 'bodySubtext', title: 'Body Subtext', type: 'text', rows: 3, hidden: ({ document }) => document?.pageId !== 'lamesa' }),
    defineField({ name: 'bodyImage', title: 'Body Image', type: 'image', options: { hotspot: true }, hidden: ({ document }) => document?.pageId !== 'lamesa' }),
    defineField({
      name: 'eyebrowLabel',
      title: 'Eyebrow Label',
      type: 'string',
      description: 'Small text displayed above the page heading',
      hidden: ({ document }) => document?.pageId !== 'filipiniana',
    }),
    defineField({
      name: 'badgeLabel',
      title: 'Card Badge Label',
      type: 'string',
      description: 'Badge text shown on each item card (e.g. "Heritage")',
      hidden: ({ document }) => document?.pageId !== 'filipiniana',
    }),
    defineField({
      name: 'cardOverlayText',
      title: 'Card Hover Overlay Text',
      type: 'string',
      description: 'Text shown on the hover overlay of each card (e.g. "View Heritage Details")',
      hidden: ({ document }) => document?.pageId !== 'filipiniana',
    }),
    defineField({
      name: 'emptyStateText',
      title: 'Empty State Text',
      type: 'string',
      description: 'Text shown when no items are found for a section/category',
      hidden: ({ document }) => document?.pageId !== 'filipiniana',
    }),
    defineField({
      name: 'soldOutText',
      title: 'Sold Out Text',
      type: 'string',
      description: 'Text shown on out-of-stock items (e.g. "Sold Out")',
      hidden: ({ document }) => document?.pageId !== 'filipiniana',
    }),
    defineField({
      name: 'card1Title',
      title: 'Intro Card 1 — Title',
      type: 'string',
      description: 'First narrative card title (e.g. "Kasuotan")',
      hidden: ({ document }) => document?.pageId !== 'filipiniana',
    }),
    defineField({
      name: 'card1Description',
      title: 'Intro Card 1 — Description',
      type: 'text',
      rows: 3,
      hidden: ({ document }) => document?.pageId !== 'filipiniana',
    }),
    defineField({
      name: 'card2Title',
      title: 'Intro Card 2 — Title',
      type: 'string',
      description: 'Second narrative card title (e.g. "Alaala")',
      hidden: ({ document }) => document?.pageId !== 'filipiniana',
    }),
    defineField({
      name: 'card2Description',
      title: 'Intro Card 2 — Description',
      type: 'text',
      rows: 3,
      hidden: ({ document }) => document?.pageId !== 'filipiniana',
    }),
    defineField({
      name: 'card3Title',
      title: 'Intro Card 3 — Title',
      type: 'string',
      description: 'Third narrative card title (e.g. "At Iba Pa")',
      hidden: ({ document }) => document?.pageId !== 'filipiniana',
    }),
    defineField({
      name: 'card3Description',
      title: 'Intro Card 3 — Description',
      type: 'text',
      rows: 3,
      hidden: ({ document }) => document?.pageId !== 'filipiniana',
    }),
  ],
  preview: {
    select: { title: 'title', subtitle: 'pageId' },
  },
})
